name: Docker Image Varnish
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/varnish/**
    branches:
      - develop
jobs:
  varnish:
    name: Varnish

    strategy:
      fail-fast: false
      matrix:
        version: ["6.0", "6.5", "6.6", "7.0"]
        multiarch: ["true"]
        include:
          - version: "4.1"
            multiarch: "false"
          - version: "6.4"
            multiarch: "false"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (amd64, arm64)
        uses: docker/build-push-action@v2
        if: ${{ matrix.multiarch == 'true' }}
        with:
          context: images/varnish/context
          file: images/varnish/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/wardenenv/varnish:${{ matrix.version }}

      - name: Build and push (amd64 only)
        uses: docker/build-push-action@v2
        if: ${{ matrix.multiarch == 'false' }}
        with:
          context: images/varnish/context
          file: images/varnish/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: docker.io/wardenenv/varnish:${{ matrix.version }}
