name: Docker Image MariaDB
on: workflow_dispatch
jobs:
  mariadb:
    name: MariaDB
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: mariadb
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
