name: Docker Image PHP-FPM
on:
  schedule:
  - cron: "0 6 * * 1"   # 6 AM UTC on Monday
  push:
    paths:
    - version
    - images/.trigger
    - images/php-fpm/**
    branches:
    - develop
jobs:
  php-fpm:
    name: FPM ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["5.5", "5.6", "7.0", "7.1", "7.2", "7.3", "7.4"]
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm
        PHP_VERSION: ${{ matrix.php_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  magento1:
    name: PHP-FPM ${{ matrix.php_version }} (magento1)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["5.5", "5.6", "7.0", "7.1", "7.2", "7.3", "7.4"]
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm/magento1
        PHP_VERSION: ${{ matrix.php_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  magento2:
    name: PHP-FPM ${{ matrix.php_version }} (magento2)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.0", "7.1", "7.2", "7.3", "7.4"]
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm/magento2
        PHP_VERSION: ${{ matrix.php_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
