name: Docker Image RabbitMQ
on: workflow_dispatch
jobs:
  rabbitmq:
    name: RabbitMQ
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: rabbitmq
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
